services:
  db:
    image: postgres:16
    container_name: microblog-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microblog_db
    ports:
      - "5432:5432"
    volumes:
      # Esta línea mantiene los datos de la DB persistentes
      - postgres-data:/var/lib/postgresql/data
      # --- INICIO DE LA CORRECCIÓN ---
      # Esta nueva línea copia nuestro schema.sql al directorio de inicialización de Postgres.
      # Se ejecutará solo la primera vez que se cree la base de datos.
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      # --- FIN DE LA CORRECCIÓN ---
    restart: unless-stopped

  cache:
    image: redis:7
    container_name: microblog-cache
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    container_name: microblog-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_ENV: prod
      SERVER_PORT: 8080
      DATABASE_URL: "postgres://user:password@db:5432/microblog_db?sslmode=disable"
      REDIS_URL: "redis://cache:6379/0"
    depends_on:
      - db
      - cache
    restart: on-failure

volumes:
  postgres-data: